### ISSUE TITLE
this plugin made allot lagg

### ISSUE THREAD

**Issue by Driesboy** [MudEGG/ArtisticVideo-VideoPlayerPlugin#2]

**Comment by flaxues** [comment]
Ofc this is lagging it need to remove place blocks everytime...

**Comment by MudEGG** [comment]
Yep,the plugin truly made allot lagg for now(Uh,But I still think a normal server can hold it in php7)
I will try to update the updating way...The early versions of the plugin update every block.
And of course it's unnecessary,so I will have this solved latter.

**Comment by Driesboy** [comment]
I use php7

Verstuurd vanaf mijn iPad
