### ISSUE TITLE
CharPlayer

### ISSUE THREAD

**Issue by flaxues** [MudEGG/ArtisticVideo-VideoPlayerPlugin#3]
If I want to use CharPlayer I'm getting this:
![3c0fadd2abe58fbb9b9ce6c03e2095f7](https://cloud.githubusercontent.com/assets/3885070/14414106/16aa4ecc-ff8d-11e5-93dd-91166f555bb4.png)

**Comment by XShockinFireX** [comment]
@flaxues Tap the space bar and it should work.

**Comment by MudEGG** [comment]
If you want to solve this,try to change your system language to Chinese.
Or if you just want to use it,please watch the video here & just follow it:https://www.youtube.com/watch?v=7nUwfnyQCLg
